services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1997
      - POSTGRES_DB=devpulse
    ports:
      - "5432:5432"
    volumes:
      - devpulse_db_data:/var/lib/postgresql/data

volumes:
  devpulse_db_data: