"""commits, reviews, sync_logs tables created

Revision ID: 4e71e6599ac0
Revises: 925142cb54e1
Create Date: 2026-07-14 14:53:53.034579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e71e6599ac0'
down_revision: Union[str, Sequence[str], None] = '925142cb54e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('prs_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviews_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('commits_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_sync_logs_status'),
    sa.CheckConstraint("triggered_by IN ('manual', 'webhook', 'scheduled')", name='ck_sync_logs_triggered_by'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name='fk_sync_logs_repository_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_repository_id'), 'sync_logs', ['repository_id'], unique=False)
    op.create_index('ix_sync_logs_started_at_desc', 'sync_logs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['contributors.id'], name='fk_commits_author_id'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name='fk_commits_repository_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha', 'repository_id', name='uq_commits_sha_repository')
    )
    op.create_index(op.f('ix_commits_author_id'), 'commits', ['author_id'], unique=False)
    op.create_index('ix_commits_committed_at_desc', 'commits', [sa.literal_column('committed_at DESC')], unique=False)
    op.create_index(op.f('ix_commits_repository_id'), 'commits', ['repository_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('github_review_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state IN ('approved', 'changes_requested', 'commented')", name='ck_reviews_state'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name='fk_reviews_pull_request_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['contributors.id'], name='fk_reviews_reviewer_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_review_id')
    )
    op.create_index(op.f('ix_reviews_pull_request_id'), 'reviews', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_submitted_at'), 'reviews', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_submitted_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_pull_request_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_commits_repository_id'), table_name='commits')
    op.drop_index('ix_commits_committed_at_desc', table_name='commits')
    op.drop_index(op.f('ix_commits_author_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index('ix_sync_logs_started_at_desc', table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_repository_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
