"""add is_onboarded to user_preferences

Revision ID: 886b44575195
Revises: 3f0d6420717e
Create Date: 2026-07-07 18:46:12.373441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886b44575195'
down_revision: Union[str, Sequence[str], None] = '3f0d6420717e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('is_onboarded', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'is_onboarded')
    # ### end Alembic commands ###
