"""create contributors,pull_requests, pr_labels and pull_request_reviewers

Revision ID: 925142cb54e1
Revises: d2790a5eda95
Create Date: 2026-07-09 17:04:23.884584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925142cb54e1'
down_revision: Union[str, Sequence[str], None] = 'd2790a5eda95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('github_login', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id', 'repository_id', name='uq_github_id_repository_id')
    )
    op.create_index(op.f('ix_contributors_repository_id'), 'contributors', ['repository_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('first_review_at', sa.DateTime(), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('additions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deletions', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("state IN ('open','closed','merged')", name='ck_pr_state'),
    sa.ForeignKeyConstraint(['author_id'], ['contributors.id'], name='fk_pull_requests_author_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name='fk_pull_requests_repository_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_pr_number', 'repository_id', name='uq_github_pr_number_repository_id')
    )
    op.create_index(op.f('ix_pull_requests_author_id'), 'pull_requests', ['author_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index('ix_pull_requests_repository_opened_at', 'pull_requests', ['repository_id', 'opened_at'], unique=False)
    op.create_index(op.f('ix_pull_requests_state'), 'pull_requests', ['state'], unique=False)
    op.create_table('pr_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name='fk_pr_labels_pull_request_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'pull_request_id', name='uq_name_pull_request_id')
    )
    op.create_index(op.f('ix_pr_labels_pull_request_id'), 'pr_labels', ['pull_request_id'], unique=False)
    op.create_table('pull_request_reviewers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('approved','changes_requested')", name='ck_pull_request_reviewers_status'),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], name='fk_pull_request_reviewers_contributor_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name='fk_pull_request_reviewers_pull_request_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'contributor_id', name='uq_pull_request_id_contributor_id')
    )
    op.create_index(op.f('ix_pull_request_reviewers_contributor_id'), 'pull_request_reviewers', ['contributor_id'], unique=False)
    op.create_index('ix_pull_request_reviewers_pr_contributor_id', 'pull_request_reviewers', ['pull_request_id', 'contributor_id'], unique=False)
    op.create_index(op.f('ix_pull_request_reviewers_pull_request_id'), 'pull_request_reviewers', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_request_reviewers_status'), 'pull_request_reviewers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_request_reviewers_status'), table_name='pull_request_reviewers')
    op.drop_index(op.f('ix_pull_request_reviewers_pull_request_id'), table_name='pull_request_reviewers')
    op.drop_index('ix_pull_request_reviewers_pr_contributor_id', table_name='pull_request_reviewers')
    op.drop_index(op.f('ix_pull_request_reviewers_contributor_id'), table_name='pull_request_reviewers')
    op.drop_table('pull_request_reviewers')
    op.drop_index(op.f('ix_pr_labels_pull_request_id'), table_name='pr_labels')
    op.drop_table('pr_labels')
    op.drop_index(op.f('ix_pull_requests_state'), table_name='pull_requests')
    op.drop_index('ix_pull_requests_repository_opened_at', table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_contributors_repository_id'), table_name='contributors')
    op.drop_table('contributors')
    # ### end Alembic commands ###
