"""drop_pull_request_reviewers_table

Revision ID: ac7016234829
Revises: 7d94bc0cba13
Create Date: 2026-07-14 21:29:33.942286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac7016234829'
down_revision: Union[str, Sequence[str], None] = '7d94bc0cba13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_request_reviewers_contributor_id'), table_name='pull_request_reviewers')
    op.drop_index(op.f('ix_pull_request_reviewers_pr_contributor_id'), table_name='pull_request_reviewers')
    op.drop_index(op.f('ix_pull_request_reviewers_pull_request_id'), table_name='pull_request_reviewers')
    op.drop_index(op.f('ix_pull_request_reviewers_status'), table_name='pull_request_reviewers')
    op.drop_table('pull_request_reviewers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request_reviewers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pull_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contributor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['approved'::character varying, 'changes_requested'::character varying]::text[])", name=op.f('ck_pull_request_reviewers_status')),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], name=op.f('fk_pull_request_reviewers_contributor_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('fk_pull_request_reviewers_pull_request_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pull_request_reviewers_pkey')),
    sa.UniqueConstraint('pull_request_id', 'contributor_id', name=op.f('uq_pull_request_id_contributor_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pull_request_reviewers_status'), 'pull_request_reviewers', ['status'], unique=False)
    op.create_index(op.f('ix_pull_request_reviewers_pull_request_id'), 'pull_request_reviewers', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_request_reviewers_pr_contributor_id'), 'pull_request_reviewers', ['pull_request_id', 'contributor_id'], unique=False)
    op.create_index(op.f('ix_pull_request_reviewers_contributor_id'), 'pull_request_reviewers', ['contributor_id'], unique=False)
    # ### end Alembic commands ###
