name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: curl -f https://veltro-62z9.onrender.com